services:
  postgres:
    image: postgres:16
    container_name: app-hockey-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_hockey
      POSTGRES_USER: app_hockey_user
      POSTGRES_PASSWORD: app_hockey_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
